version: '3.8'

services:
  doorbell-security:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DEVELOPMENT_MODE=true
      - PORT=5000
      - FLASK_ENV=development
    volumes:
      # Mount data directories for persistence
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: Add a simple reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - doorbell-security
    restart: unless-stopped
    profiles:
      - production
