[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/status"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
DEVELOPMENT_MODE = "true"
RAILWAY = "true"
PORT = "8080"
