version: '3.8'

services:
  # Application service
  doorbell-system:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile.production
    image: doorbell-system:production
    container_name: doorbell-system-prod
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
      - DEBUG=False
      - MONITORING_ENABLED=True
      - PROMETHEUS_PORT=8000
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
      - WORKER_PROCESSES=4
      - WORKER_THREADS=2
    ports:
      - "5000:5000"
      - "8000:8000"
    volumes:
      - app-data:/app/data
      - app-logs:/app/data/logs
      - app-backups:/app/data/backups
    healthcheck:
      test: ["CMD", "/health_check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - doorbell-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Prometheus monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - doorbell-network

  # Grafana dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - doorbell-network
    depends_on:
      - prometheus

networks:
  doorbell-network:
    driver: bridge

volumes:
  app-data:
  app-logs:
  app-backups:
  prometheus-data:
  grafana-data:
