# Prometheus Configuration for Doorbell Security System

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'doorbell-system'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - 'alertmanager:9093'

# Rule files
rule_files:
  # - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Doorbell System application metrics
  - job_name: 'doorbell-system'
    static_configs:
      - targets: ['doorbell-system:8000']
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/metrics'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
